language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - "npm run test:unit"
  - "npm run test:unit:coverage"

after_script:
  - cat ./jest/coverage/lcov-report | coveralls