language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - "npm run test:unit"
  - "npm run test:unit:coveralls"

notifications:
  # Turn off email notifications entirely.
  email: false